/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package vista;

/**
 *
 * @author peace
 */
public class FrmInsertar extends javax.swing.JFrame {

    /** Creates new form Insertar */
    public FrmInsertar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensaje = new javax.swing.JOptionPane();
        jpFfondo = new javax.swing.JPanel();
        btnCancelarRegistro = new javax.swing.JButton();
        btnRgistrar = new javax.swing.JButton();
        txtPoblacion = new javax.swing.JTextField();
        lbpoblacion = new javax.swing.JLabel();
        txtCapital = new javax.swing.JTextField();
        lbCapital = new javax.swing.JLabel();
        txtNombrePais = new javax.swing.JTextField();
        lbNombrePais = new javax.swing.JLabel();
        lblRegistrarPais = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar");

        jpFfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regsimg/cancelar (1).png"))); // NOI18N
        btnCancelarRegistro.setText("Cancelar");
        jpFfondo.add(btnCancelarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 120, 30));

        btnRgistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regsimg/portapapeles.png"))); // NOI18N
        btnRgistrar.setText("Registrar");
        jpFfondo.add(btnRgistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, 30));

        txtPoblacion.setBackground(new java.awt.Color(204, 204, 204));
        txtPoblacion.setForeground(new java.awt.Color(0, 0, 0));
        jpFfondo.add(txtPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 280, 30));

        lbpoblacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbpoblacion.setForeground(new java.awt.Color(153, 153, 153));
        lbpoblacion.setText("Población:");
        jpFfondo.add(lbpoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, 30));

        txtCapital.setBackground(new java.awt.Color(204, 204, 204));
        txtCapital.setForeground(new java.awt.Color(0, 0, 0));
        txtCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapitalActionPerformed(evt);
            }
        });
        jpFfondo.add(txtCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 280, 30));

        lbCapital.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCapital.setForeground(new java.awt.Color(153, 153, 153));
        lbCapital.setText("Capital:");
        jpFfondo.add(lbCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 30));

        txtNombrePais.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePais.setForeground(new java.awt.Color(0, 0, 0));
        txtNombrePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePaisActionPerformed(evt);
            }
        });
        jpFfondo.add(txtNombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 280, 30));

        lbNombrePais.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbNombrePais.setForeground(new java.awt.Color(153, 153, 153));
        lbNombrePais.setText("Nombre del país:");
        jpFfondo.add(lbNombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, 30));

        lblRegistrarPais.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblRegistrarPais.setForeground(new java.awt.Color(153, 153, 153));
        lblRegistrarPais.setText("Registrar Pais");
        jpFfondo.add(lblRegistrarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regsimg/planeta-mundo.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        lblFondo.setOpaque(true);
        jpFfondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 250));

        getContentPane().add(jpFfondo, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePaisActionPerformed

    private void txtCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapitalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInsertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarRegistro;
    public javax.swing.JButton btnRgistrar;
    public javax.swing.JOptionPane jopMensaje;
    private javax.swing.JPanel jpFfondo;
    private javax.swing.JLabel lbCapital;
    private javax.swing.JLabel lbNombrePais;
    public javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblRegistrarPais;
    private javax.swing.JLabel lbpoblacion;
    public javax.swing.JTextField txtCapital;
    public javax.swing.JTextField txtNombrePais;
    public javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables

}
